export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const CREATE_PROJECTS_SUCCESS = "CREATE_PROJECTS_SUCCESS";

export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";

export const CHANGE_LANGUAGE_SUCCESS = "CHANGE_LANGUAGE_SUCCESS";